name: Backend Deploy

on:
  push:
    branches: [ deploy-backend ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/actions-runner/frontend/rit-cage/backend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd /home/actions-runner/frontend/rit-cage/backend
    - run: npm i
    - run: npm run build --if-present

