name: Backend Deploy
on:
  push:
    branches: [ deploy-backend ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    # - run: cd /opt/webserver
    - run: cp -r * /opt/webserver && rm -rf /home/actions-runner/frontend/rit-cage/rit-cage/*
    - run: pm2 restart Backend
