name: BackendDeploy
on:
  push:
    branches: [ deploy-backend ]

defaults:
  run:
    working-directory: /opt/webserver

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    # - run: cp -a /home/actions-runner/frontend/rit-cage/. /opt/webserver
    # - run: cd /opt/webserver
    # - run: pm2 restart Backend
